### ISSUE TITLE
prevent redundant OGM creation attempts

### ISSUE THREAD

**Issue by ehrenb** [ehrenb/machina#17]
Currently, each worker attempts to initialize the OGM.  While no duplicate OGMs will be created, it does cause significant delay in start time.  There should be one dedicated service to init the OGMs, or a check to see if the OGM exists before init.

OrientDB shows the following error:

```bash
2022-12-25 16:30:39:479 SEVER Exception `5EA22C9A` in storage `plocal:/orientdb/databases/machina`: 3.2.13 (build 1b0940491143c734d9f7338b321c2cde319a79ef, branch UNKNOWN) [OLocalPaginatedStorage]
com.orientechnologies.orient.core.exception.OCommandExecutionException: Property 'apk.md5' already exists. Remove it before to retry.
	DB name="machina"
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateProperty.execute(OCommandExecutorSQLCreateProperty.java:298)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:4205)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:4171)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommand(OConnectionBinaryExecutor.java:618)
```

- [x] In workers, use https://github.com/mogui/pyorient/blob/fb74c5da75c14b568c79949b219b98549d1c732a/pyorient/ogm/graph.py#L101 to bind the class OGM

- [x] Create an Initializer that performs the create_all https://github.com/mogui/pyorient/blob/fb74c5da75c14b568c79949b219b98549d1c732a/pyorient/ogm/graph.py#L527

**Comment by ehrenb** [comment]
- [ ] In workers, use https://github.com/mogui/pyorient/blob/fb74c5da75c14b568c79949b219b98549d1c732a/pyorient/ogm/graph.py#L101 to bind the class OGM

- []] Create an Initializer that performs the create_all https://github.com/mogui/pyorient/blob/fb74c5da75c14b568c79949b219b98549d1c732a/pyorient/ogm/graph.py#L527
