### ISSUE TITLE
PyOrientSecurityAccessException

### ISSUE THREAD

**Issue by ehrenb** [ehrenb/machina#23]
After some time (20 minutes) of analyzing a jffs2, workers start throwing the following error:

```bash
Exception in thread Thread-3820 (callback):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/machina/src/identifier.py", line 137, in callback
    origin_node = self.graph.get_vertex(data['origin']['id'])
  File "/usr/lib/python3.10/site-packages/pyorient/ogm/graph.py", line 612, in get_vertex
    record = self.client.command('SELECT FROM {}'.format(vertex_id))
  File "/usr/lib/python3.10/site-packages/pyorient/orient.py", line 481, in command
    return self.get_message("CommandMessage").prepare((QUERY_CMD,) + args).send().fetch_response()
  File "/usr/lib/python3.10/site-packages/pyorient/messages/commands.py", line 143, in fetch_response
    super(CommandMessage, self).fetch_response()
  File "/usr/lib/python3.10/site-packages/pyorient/messages/database.py", line 300, in fetch_response
    self._decode_all()
  File "/usr/lib/python3.10/site-packages/pyorient/messages/database.py", line 283, in _decode_all
    self._decode_header()
  File "/usr/lib/python3.10/site-packages/pyorient/messages/database.py", line 229, in _decode_header
    raise PyOrientCommandException(
pyorient.exceptions.PyOrientSecurityAccessException: com.orientechnologies.orient.core.exception.OSecurityAccessException - Invalid authentication info for access to the database com.orientechnologies.orient.core.metadata.security.auth.OTokenAuthInfo@18287ceb
	DB name="machina"
```

**Comment by ehrenb** [comment]
moving to neo4j
