### ISSUE TITLE
binwalk upgrade

### ISSUE THREAD

**Issue by ehrenb** [ehrenb/machina#45]
Binwalk has been re-written in Rust (https://github.com/ReFirmLabs/binwalk).

**Comment by ehrenb** [comment]
Really need to upgrade now that using Python3.12

```bash
Traceback (most recent call last):
  File "/machina/src/run.py", line 3, in <module>
    from binwalkanalysis import BinwalkAnalysis
  File "/machina/src/binwalkanalysis.py", line 9, in <module>
    import binwalk
  File "/usr/local/lib/python3.12/dist-packages/binwalk-2.3.3-py3.12.egg/binwalk/__init__.py", line 3, in <module>
    from binwalk.core.module import Modules
  File "/usr/local/lib/python3.12/dist-packages/binwalk-2.3.3-py3.12.egg/binwalk/core/module.py", line 18, in <module>
    import binwalk.core.plugin
  File "/usr/local/lib/python3.12/dist-packages/binwalk-2.3.3-py3.12.egg/binwalk/core/plugin.py", line 4, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

```
The
ModuleNotFoundError for the imp module when running binwalk occurs because the imp module was deprecated in Python 3.4 and removed entirely in Python 3.12. The issue is with older binwalk code that still uses the imp module. 
```
